pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            jenkins: slave
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: busybox
            image: busybox
            command:
            - cat
            tty: true
        '''
      retries 2
    }
  }
  stages {
    stage('Run maven') {
        steps{
            container('maven') {
                sh 'mvn -version'
                sh 'pwd'
                sh 'ls -l'
            }
        }
    }
    stage('Run busybox') {
        steps{
            container('busybox') {
                sh 'pwd'
                sh 'ls -l'
                sh '/bin/busybox'
            }
        }
    }
  }
}